### ISSUE TITLE
cgminer can not work with bi*fury stick // failed to initialise dev

### ISSUE THREAD

**Issue by deagel** [MineForeman/minepeon-base#13]
[2013-12-19 17:53:50] bitfury detect (1:10) failed to initialise (incorrect dev
 [2013-12-19 17:53:56] USB init, open device failed, err -3, you don't have priv
 [2013-12-19 17:53:56] See README file included for help
 [2013-12-19 17:53:56] bitfury detect (1:10) failed to initialise (incorrect dev
 [2013-12-19 17:54:03] USB init, open device failed, err -3, you don't have priv
 [2013-12-19 17:54:03] See README file included for help
 [2013-12-19 17:54:03] bitfury detect (1:10) failed to initial

On windows with version cgminer 3.8.5 it wok without issues. Can you recompile with support of bi*fury?

**Comment by deagel** [comment]
hi,
i changed user minepeon to root in:
/usr/lib/systemd/system/miner.service

know the bi*fury is running but it is a bad workaround.

**Comment by MineForeman** [comment]
Can you do a;-

lsusb -v

As root for me and post back the results, it seems that I might have a few problems with my uDev rules.

Neil

**Comment by deagel** [comment]
Hi,
Here is the Output:

lsusb -v                                                                                                                        Bus 001 Device 011: ID 198c:b1f1                               Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass            2 Communications                       bDeviceSubClass         0                                      bDeviceProtocol         0                                      bMaxPacketSize0        64                                      idVendor           0x198c                                      idProduct          0xb1f1                                      bcdDevice            0.00                                      iManufacturer           1 c-scape                              iProduct                2 bi?fury                              iSerial                 3 121219280254094                      bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           62                                      bNumInterfaces          2                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0x80                                        (Bus Powered)                                                MaxPower              500mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           1                                      bInterfaceClass         2 Communications                       bInterfaceSubClass      2 Abstract (modem)                     bInterfaceProtocol      1 AT-commands (v.25ter)                iInterface              0                                      CDC Header:                                                      bcdCDC               1.10                                    CDC ACM:                                                         bmCapabilities       0x06                                        sends break                                                    line coding and serial state                               CDC Union:                                                       bMasterInterface        0                                      bSlaveInterface         1                                    Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0008  1x 8 bytes                          bInterval             255                                  Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        1                                      bAlternateSetting       0                                      bNumEndpoints           2                                      bInterfaceClass        10 CDC Data                             bInterfaceSubClass      0 Unused                               bInterfaceProtocol      0                                      iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x02  EP 2 OUT                            bmAttributes            2                                        Transfer Type            Bulk                                  Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0040  1x 64 bytes                         bInterval               0                                    Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x82  EP 2 IN                             bmAttributes            2                                        Transfer Type            Bulk                                  Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0040  1x 64 bytes                         bInterval               0                              Device Status:     0x0000                                        (Bus Powered)                                                                                                               Bus 001 Device 007: ID 0835:8502 Action Star Enterprise Co., Ltd                                                              Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass            0 (Defined at Interface level)         bDeviceSubClass         0                                      bDeviceProtocol         0                                      bMaxPacketSize0        64                                      idVendor           0x0835 Action Star Enterprise Co., Ltd      idProduct          0x8502                                      bcdDevice            6.05                                      iManufacturer           1 Action Star                          iProduct                2 USB HID                              iSerial                 0                                      bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           34                                      bNumInterfaces          1                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0xc0                                        Self Powered                                                 MaxPower               20mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           1                                      bInterfaceClass         3 Human Interface Device               bInterfaceSubClass      1 Boot Interface Subclass              bInterfaceProtocol      1 Keyboard                             iInterface              0                                        HID Device Descriptor:                                           bLength                 9                                      bDescriptorType        33                                      bcdHID               1.11                                      bCountryCode            0 Not supported                        bNumDescriptors         1                                      bDescriptorType        34 Report                               wDescriptorLength      35                                     Report Descriptors:                                              *\* UNAVAILABLE *\*                                         Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x82  EP 2 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0008  1x 8 bytes                          bInterval               8                              Device Qualifier (for other device speed):                       bLength                10                                      bDescriptorType         6                                      bcdUSB               2.00                                      bDeviceClass            0 (Defined at Interface level)         bDeviceSubClass         0                                      bDeviceProtocol         0                                      bMaxPacketSize0        64                                      bNumConfigurations      1                                    Device Status:     0x0002                                        (Bus Powered)                                                  Remote Wakeup Enabled                                                                                                       Bus 001 Device 006: ID 0835:8500 Action Star Enterprise Co., Ltd                                                              Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass            9 Hub                                  bDeviceSubClass         0 Unused                               bDeviceProtocol         2 TT per port                          bMaxPacketSize0        64                                      idVendor           0x0835 Action Star Enterprise Co., Ltd      idProduct          0x8500                                      bcdDevice            1.06                                      iManufacturer           1 Action Star                          iProduct                2 USB2.0 Hub                           iSerial                 0                                      bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           41                                      bNumInterfaces          1                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0xe0                                        Self Powered                                                   Remote Wakeup                                                MaxPower              100mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           1                                      bInterfaceClass         9 Hub                                  bInterfaceSubClass      0 Unused                               bInterfaceProtocol      1 Single TT                            iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0001  1x 1 bytes                          bInterval              12                                  Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       1                                      bNumEndpoints           1                                      bInterfaceClass         9 Hub                                  bInterfaceSubClass      0 Unused                               bInterfaceProtocol      2 TT per port                          iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0001  1x 1 bytes                          bInterval              12                              Hub Descriptor:                                                  bLength               9                                        bDescriptorType      41                                        nNbrPorts             5                                        wHubCharacteristic 0x00e4                                        Ganged power switching                                         Compound device                                                Ganged overcurrent protection                                  TT think time 32 FS bits                                       Port indicators                                              bPwrOn2PwrGood       50 \* 2 milli seconds                      bHubContrCurrent    100 milli Ampere                           DeviceRemovable    0x00                                        PortPwrCtrlMask    0xff                                       Hub Port Status:                                                 Port 1: 0000.0503 highspeed power enable connect               Port 2: 0000.0100 power                                        Port 3: 0000.0100 power                                        Port 4: 0000.0103 power enable connect                         Port 5: 0000.0100 power                                     Device Qualifier (for other device speed):                       bLength                10                                      bDescriptorType         6                                      bcdUSB               2.00                                      bDeviceClass            9 Hub                                  bDeviceSubClass         0 Unused                               bDeviceProtocol         0 Full speed (or root) hub             bMaxPacketSize0        64                                      bNumConfigurations      1                                    Device Status:     0x0003                                        Self Powered                                                   Remote Wakeup Enabled                                                                                                       Bus 001 Device 005: ID 0835:8501 Action Star Enterprise Co., Ltd                                                              Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass            0 (Defined at Interface level)         bDeviceSubClass         0                                      bDeviceProtocol         0                                      bMaxPacketSize0        64                                      idVendor           0x0835 Action Star Enterprise Co., Ltd      idProduct          0x8501                                      bcdDevice            6.05                                      iManufacturer           1 Action Star                          iProduct                2 USB HID                              iSerial                 0                                      bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           34                                      bNumInterfaces          1                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0xc0                                        Self Powered                                                 MaxPower               20mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           1                                      bInterfaceClass         3 Human Interface Device               bInterfaceSubClass      1 Boot Interface Subclass              bInterfaceProtocol      1 Keyboard                             iInterface              0                                        HID Device Descriptor:                                           bLength                 9                                      bDescriptorType        33                                      bcdHID               1.11                                      bCountryCode            0 Not supported                        bNumDescriptors         1                                      bDescriptorType        34 Report                               wDescriptorLength      35                                     Report Descriptors:                                              *\* UNAVAILABLE *\*                                         Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x82  EP 2 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0008  1x 8 bytes                          bInterval               8                              Device Qualifier (for other device speed):                       bLength                10                                      bDescriptorType         6                                      bcdUSB               2.00                                      bDeviceClass            0 (Defined at Interface level)         bDeviceSubClass         0                                      bDeviceProtocol         0                                      bMaxPacketSize0        64                                      bNumConfigurations      1                                    Device Status:     0x0002                                        (Bus Powered)                                                  Remote Wakeup Enabled                                                                                                       Bus 001 Device 004: ID 0835:8500 Action Star Enterprise Co., Ltd                                                              Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass            9 Hub                                  bDeviceSubClass         0 Unused                               bDeviceProtocol         2 TT per port                          bMaxPacketSize0        64                                      idVendor           0x0835 Action Star Enterprise Co., Ltd      idProduct          0x8500                                      bcdDevice            1.06                                      iManufacturer           1 Action Star                          iProduct                2 USB2.0 Hub                           iSerial                 0                                      bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           41                                      bNumInterfaces          1                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0xe0                                        Self Powered                                                   Remote Wakeup                                                MaxPower              100mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           1                                      bInterfaceClass         9 Hub                                  bInterfaceSubClass      0 Unused                               bInterfaceProtocol      1 Single TT                            iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0001  1x 1 bytes                          bInterval              12                                  Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       1                                      bNumEndpoints           1                                      bInterfaceClass         9 Hub                                  bInterfaceSubClass      0 Unused                               bInterfaceProtocol      2 TT per port                          iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0001  1x 1 bytes                          bInterval              12                              Hub Descriptor:                                                  bLength               9                                        bDescriptorType      41                                        nNbrPorts             5                                        wHubCharacteristic 0x00e4                                        Ganged power switching                                         Compound device                                                Ganged overcurrent protection                                  TT think time 32 FS bits                                       Port indicators                                              bPwrOn2PwrGood       50 \* 2 milli seconds                      bHubContrCurrent    100 milli Ampere                           DeviceRemovable    0x00                                        PortPwrCtrlMask    0xff                                       Hub Port Status:                                                 Port 1: 0000.0503 highspeed power enable connect               Port 2: 0000.0100 power                                        Port 3: 0000.0100 power                                        Port 4: 0000.0100 power                                        Port 5: 0000.0503 highspeed power enable connect            Device Qualifier (for other device speed):                       bLength                10                                      bDescriptorType         6                                      bcdUSB               2.00                                      bDeviceClass            9 Hub                                  bDeviceSubClass         0 Unused                               bDeviceProtocol         0 Full speed (or root) hub             bMaxPacketSize0        64                                      bNumConfigurations      1                                    Device Status:     0x0003                                        Self Powered                                                   Remote Wakeup Enabled                                                                                                       Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter                              Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass          255 Vendor Specific Class                bDeviceSubClass         0                                      bDeviceProtocol         1                                      bMaxPacketSize0        64                                      idVendor           0x0424 Standard Microsystems Corp.          idProduct          0xec00 SMSC9512/9514 Fast Ethernet Adapter  bcdDevice            2.00                                      iManufacturer           0                                      iProduct                0                                      iSerial                 0                                      bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           39                                      bNumInterfaces          1                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0xe0                                        Self Powered                                                   Remote Wakeup                                                MaxPower                2mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           3                                      bInterfaceClass       255 Vendor Specific Class                bInterfaceSubClass      0                                      bInterfaceProtocol    255                                      iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            2                                        Transfer Type            Bulk                                  Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0200  1x 512 bytes                        bInterval               0                                    Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x02  EP 2 OUT                            bmAttributes            2                                        Transfer Type            Bulk                                  Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0200  1x 512 bytes                        bInterval               0                                    Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x83  EP 3 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0010  1x 16 bytes                         bInterval               4                              Device Qualifier (for other device speed):                       bLength                10                                      bDescriptorType         6                                      bcdUSB               2.00                                      bDeviceClass          255 Vendor Specific Class                bDeviceSubClass         0                                      bDeviceProtocol         1                                      bMaxPacketSize0        64                                      bNumConfigurations      1                                    Device Status:     0x0001                                        Self Powered                                                                                                                Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp. LAN9500 Ethernet 10/100 Adapter / SMSC9512/9514 Hub              Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass            9 Hub                                  bDeviceSubClass         0 Unused                               bDeviceProtocol         2 TT per port                          bMaxPacketSize0        64                                      idVendor           0x0424 Standard Microsystems Corp.          idProduct          0x9512 LAN9500 Ethernet 10/100 Adapter / SMSC9512/9514 Hub                                                 bcdDevice            2.00                                      iManufacturer           0                                      iProduct                0                                      iSerial                 0                                      bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           41                                      bNumInterfaces          1                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0xe0                                        Self Powered                                                   Remote Wakeup                                                MaxPower                2mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           1                                      bInterfaceClass         9 Hub                                  bInterfaceSubClass      0 Unused                               bInterfaceProtocol      1 Single TT                            iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0001  1x 1 bytes                          bInterval              12                                  Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       1                                      bNumEndpoints           1                                      bInterfaceClass         9 Hub                                  bInterfaceSubClass      0 Unused                               bInterfaceProtocol      2 TT per port                          iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0001  1x 1 bytes                          bInterval              12                              Hub Descriptor:                                                  bLength               9                                        bDescriptorType      41                                        nNbrPorts             3                                        wHubCharacteristic 0x000d                                        Per-port power switching                                       Compound device                                                Per-port overcurrent protection                                TT think time 8 FS bits                                      bPwrOn2PwrGood       50 \* 2 milli seconds                      bHubContrCurrent      1 milli Ampere                           DeviceRemovable    0x02                                        PortPwrCtrlMask    0xff                                       Hub Port Status:                                                 Port 1: 0000.0503 highspeed power enable connect               Port 2: 0000.0100 power                                        Port 3: 0000.0503 highspeed power enable connect            Device Qualifier (for other device speed):                       bLength                10                                      bDescriptorType         6                                      bcdUSB               2.00                                      bDeviceClass            9 Hub                                  bDeviceSubClass         0 Unused                               bDeviceProtocol         0 Full speed (or root) hub             bMaxPacketSize0        64                                      bNumConfigurations      1                                    Device Status:     0x0001                                        Self Powered                                                                                                                Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub Device Descriptor:                                               bLength                18                                      bDescriptorType         1                                      bcdUSB               2.00                                      bDeviceClass            9 Hub                                  bDeviceSubClass         0 Unused                               bDeviceProtocol         1 Single TT                            bMaxPacketSize0        64                                      idVendor           0x1d6b Linux Foundation                     idProduct          0x0002 2.0 root hub                         bcdDevice            3.10                                      iManufacturer           3 Linux 3.10.24-1-ARCH dwc_otg_hcd     iProduct                2 DWC OTG Controller                   iSerial                 1 bcm2708_usb                          bNumConfigurations      1                                      Configuration Descriptor:                                        bLength                 9                                      bDescriptorType         2                                      wTotalLength           25                                      bNumInterfaces          1                                      bConfigurationValue     1                                      iConfiguration          0                                      bmAttributes         0xe0                                        Self Powered                                                   Remote Wakeup                                                MaxPower                0mA                                    Interface Descriptor:                                            bLength                 9                                      bDescriptorType         4                                      bInterfaceNumber        0                                      bAlternateSetting       0                                      bNumEndpoints           1                                      bInterfaceClass         9 Hub                                  bInterfaceSubClass      0 Unused                               bInterfaceProtocol      0 Full speed (or root) hub             iInterface              0                                      Endpoint Descriptor:                                             bLength                 7                                      bDescriptorType         5                                      bEndpointAddress     0x81  EP 1 IN                             bmAttributes            3                                        Transfer Type            Interrupt                             Synch Type               None                                  Usage Type               Data                                wMaxPacketSize     0x0004  1x 4 bytes                          bInterval              12                              Hub Descriptor:                                                  bLength               9                                        bDescriptorType      41                                        nNbrPorts             1                                        wHubCharacteristic 0x0008                                        Ganged power switching                                         Per-port overcurrent protection                                TT think time 8 FS bits                                      bPwrOn2PwrGood        1 \* 2 milli seconds                      bHubContrCurrent      0 milli Ampere                           DeviceRemovable    0x00                                        PortPwrCtrlMask    0xff                                       Hub Port Status:                                                 Port 1: 0000.0503 highspeed power enable connect            Device Status:     0x0001                                        Self Powered                                              

Von meinem iPhone gesendet

> Am 19.12.2013 um 22:58 schrieb MineForeman notifications@github.com:
> 
> lsusb -v

**Comment by deagel** [comment]
hi,
i found a hint at:
https://github.com/ckolivas/cgminer/blob/master/README

search for root.

it look like a simple permission problem.

**Comment by deagel** [comment]
me again,
i found it.

in the file /etc/udev/rules.d/01-miner.rules following line was missed:

# BXF

ATTRS{idVendor}=="198c", ATTRS{idProduct}=="b1f1", SUBSYSTEMS=="usb", ACTION=="add", MODE="0666", GROUP="plugdev"

I have seen that there are other lines with GROUP="plugdev", the group did not existing on my minepeon i switched it to minepeon.

regards,
deagel

**Comment by phillpafford** [comment]
running the command 

```
 sudo lsusb -v
```

I get this out put, is this correct?

  idVendor           0x03eb Atmel Corp.
  idProduct          0x204b LUFA USB to Serial Adapter Project
  bcdDevice            0.00
  iManufacturer           1 BFMG
  iProduct                2 Bitfury BF1

```
# BF1
ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="204b", SUBSYSTEMS=="usb", ACTION=="add", MODE="0666", GROUP="minepeon"
```

adding this line to the file

```
/etc/udev/rules.d/01-miner.rules
```

rebooted the server and now I see my miner!

**Comment by MineForeman** [comment]
Hi All,

Thanks for the addition!  UDEV rules are now (since 0.2.5 RC1) kept in their own repo along with the skeleton build of config files;-

https://github.com/MineForeman/minepeon-skel

Specifically you will find them in this file;-

https://github.com/MineForeman/minepeon-skel/blob/master/etc/udev/rules.d/01-miner.rules

That one has been added but feel free to add others you find.
