### ISSUE TITLE
ADD Stratum mining proxy 

### ISSUE THREAD

**Issue by deagel** [MineForeman/minepeon-base#14]
Can you add a Stratum Proxy like:
https://github.com/slush0/stratum-mining-proxy
https://mining.bitcoin.cz/stratum-mining

bfgminer did actual not support bi*fury and cgminer did not have a proxy function.

**Comment by MineForeman** [comment]
It could be done using a plugin, there is some development going on there that will make it quite easy.

I will add it to my ever growing TODO list (unless someone else gets to it first).

Neil
