### ISSUE TITLE
[Bug] Switch pool not working

### ISSUE THREAD

**Issue by mariogrip** [MineForeman/minepeon-base#27]
I have tried to find the problem, seems like it something with bfgminer... It cannot send "switchpool" command to bfgminer. I don't know if it is a permission problem or luke-jr have edit something in the api, btw that's why the donate drops.

**Comment by MineForeman** [comment]
I had not noticed.. that is an annoying issue especial since we just pushed out that feature.

It is not consistent though, immediately after rebooting it will switch fine.  It is only after some time that it will no longer switch the pool.

**Comment by MineForeman** [comment]
Further findings, bfgminer will let you switchpool once and then your locked.  I will asked Luke for help.

https://bitcointalk.org/index.php?topic=168174.msg5580207#msg5580207

**Comment by mariogrip** [comment]
Humm, readme.rpc at luke-jr's github it says  

switchpool|N 
The Msg includes the pool URL
Msg=string
Message matching the Code value N

**Comment by MineForeman** [comment]
Are you reading from;-

https://github.com/luke-jr/bfgminer/blob/bfgminer/README.RPC

what I see is;-

 switchpool|N (*)
               none           There is no reply section just the STATUS section
                              stating the results of switching pool N to the
                              highest priority (the pool is also enabled)
                              The Msg includes the pool URL

and that is the same as the cgminer api.

**Comment by mariogrip** [comment]
Ah, when i try to send switchpool command i get 
Access denied to 'switchpool' command

**Comment by MineForeman** [comment]
Do you have;-

"api-allow": "W:127.0.0.1",

In your miner.conf file?

**Comment by mariogrip** [comment]
in miner.conf? Humm, that is not added automatically.

**Comment by mariogrip** [comment]
Add this to f_pools_save.php then it will work  
        $data['api-allow'] = "127.0.0.1";
        $data['api-listen'] = true;
        $data['api-allow'] = "W:127.0.0.1";

**Comment by MineForeman** [comment]
miner.conf is shipped with with the setting.

Are you saying;

$data['api-allow'] = "127.0.0.1";
$data['api-listen'] = true;
$data['api-allow'] = "W:127.0.0.1";

Fixes the problem?

**Comment by mariogrip** [comment]
yeah, I have tested it.

Now if i delete miner.conf, it will create a new one

**Comment by MineForeman** [comment]
Sorry, do you mean it fixes the bfgminer problem?

**Comment by mariogrip** [comment]
Yeah, I send a pull request, that is working for me.

**Comment by mariogrip** [comment]
It looks like this bug is solved, but we got another problem, i got a report that the miner is not changing to Donate pool.

http://minepeon.com/forums/viewtopic.php?f=4&t=1424
