### ISSUE TITLE
[Bug] miner is not changing to Donate pool.

### ISSUE THREAD

**Issue by mariogrip** [MineForeman/minepeon-base#30]
i got a report that the miner is not changing to Donate pool. 

http://minepeon.com/forums/viewtopic.php?f=4&t=1424

I will publish bugs here so we can solve them together. (sounds good?)

**Comment by mariogrip** [comment]
solved :)
![screenshot from 2014-03-08 17 51 45](https://f.cloud.github.com/assets/1642635/2365850/c108ce58-a6e2-11e3-93e3-fa500a45bde5.png)

**Comment by MineForeman** [comment]
Do you think there are any oustanding issues to solve before we put out a new version?

**Comment by mariogrip** [comment]
everything looks fine, so i guess there is no huge bugs running around.
