### ISSUE TITLE
[Bug] miner is not changing back to original pool

### ISSUE THREAD

**Issue by mariogrip** [MineForeman/minepeon-base#34]
miner is not changing back to original pool

http://minepeon.com/forums/viewtopic.php?f=4&t=1436

This might be why people is turning that off...

**Comment by MineForeman** [comment]
I just about to repliy to that thread as well.

What really needs to happen is another supervisory process in the 5 min cron job that checks that donate is turned off when it should have.  You want to take a crack at that while I go through your update patch?

Neil

**Comment by mariogrip** [comment]
Sure, I will start working on that now.

**Comment by MineForeman** [comment]
Your my freekin hero :) .

I discovered a problem when upgrading via pacman last night that total blows away php 100% of the time (it updated to apache 2.4) .  I am working on brining all the apache config files forward to 2.4 .  Something like this always happens when I plan to release.

Neil

**Comment by mariogrip** [comment]
Fixed :)

**Comment by mariogrip** [comment]
Btw, I cannot send as a separate pull request.

**Comment by MineForeman** [comment]
I saw your post about remote access, we need to talk, we are now working on the same thing.  My skype is fincham.neil .

I am at work now but add me and we will get together later.

**Comment by mariogrip** [comment]
Added you on skype.

Btw, Don't worry. i didn't do that much on that remote access.
