### ISSUE TITLE
Keyboard Issue with Raspberry Pi B+

### ISSUE THREAD

**Issue by aqeelat** [MineForeman/minepeon-base#53]
The keyboars does not work when connected to raspberry pi. I cannot login to get my ip address.
The keyboard works with other linux versions on the same raspberry.

**Comment by MineForeman** [comment]
Can you try the latest test image and see if the problem persists;-

http://minepeon.com/img/testing/RaspberryPi/MPRPI20140915-R-0.3.0-PR3.img.zip

**Comment by ghost** [comment]
this is a very simple fix if you have a raspberry pi B model around.  if you dont
i can take a stock 0.2.4.6 image and fix it to work with the B+ and somehow
get it to you.

**Comment by leomar-developer** [comment]
Does anyone has a Minepeon image that works with the Pi B+?? tried the latest image downloaded from sourceforge and seems the controllers are too old for a B+ thus the USB and Ethernet ports are not working... don't know how to fix the stock 0.2.4.6 image to make it work on a B+... could anyone help me? PiMiner perhaps? :)

**Comment by leomar-developer** [comment]
I could get it working with the MPRPI20140915-R-0.3.0-PR3.img.zip but I cant ssh to it using username: minepeon and passw: peon... does anyone knows the credentials to ssh to this minepeon img?
